"""added persona fields

Revision ID: 003
Revises: 002
Create Date: 2026-01-23 03:00:40.418050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_decisions_user_id'), table_name='purchase_decisions')
    op.add_column('users', sa.Column('persona_tone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('strictness_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'strictness_level')
    op.drop_column('users', 'persona_tone')
    op.create_index(op.f('ix_purchase_decisions_user_id'), 'purchase_decisions', ['user_id'], unique=False)
    # ### end Alembic commands ###
